version: '3.7'
services:
  api:
    container_name: api
    build:
      dockerfile: dockerfile
      context: ./api
    ports:
      - 3090:3090
    volumes:
      - /app/node_modules
      - ./api:/app  
    depends_on:
      - postgres
    links:
      - postgres       
  dashboard:
    container_name: dashboard
    build:
      dockerfile: dockerfile
      context: ./dashboard
    ports: 
        - 3000:3000
    volumes:
      - /app/node_modules
      - ./dashboard:/app
  postgres:
    restart: always
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "dev_db"
      POSTGRES_USER: "guardrails"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./api/database/script/init_test.sql:/docker-entrypoint-initdb.d/init_test.sql
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

